version: "3"

services:
  backend:
    container_name: superheroes
    restart: always
    build: /server
    link:
      -mongodb
    ports:
      -3100:3100
    networks:
      - network-backend

  mongodb:
    container_name: mongodb_database
    image: mongo
    expose:
      -27017
      -mongodb_data:/data/db
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    networks:
      - network-backend

networks:
  network-backend:
    driver: bridge
volumes:
  mongodb_data:
    external: true
